(window.webpackJsonp=window.webpackJsonp||[]).push([[24],{297:function(t,e,i){"use strict";i.r(e);var a=i(0),r=Object(a.a)({},function(){var t=this,e=t.$createElement,i=t._self._c||e;return i("ContentSlotsDistributor",{attrs:{"slot-key":t.$parent.slotKey}},[i("h1",{attrs:{id:"mysql-一些故障及解决方案"}},[i("a",{staticClass:"header-anchor",attrs:{href:"#mysql-一些故障及解决方案","aria-hidden":"true"}},[t._v("#")]),t._v(" mysql 一些故障及解决方案")]),t._v(" "),i("ul",[i("li",[t._v("本文主要记录使用 mysql 可能会碰到的一些问题，以及探索相关解决方法")])]),t._v(" "),i("h2",{attrs:{id:"lock-wait-timeout-exceeded"}},[i("a",{staticClass:"header-anchor",attrs:{href:"#lock-wait-timeout-exceeded","aria-hidden":"true"}},[t._v("#")]),t._v(" lock wait timeout exceeded")]),t._v(" "),i("ul",[i("li",[i("strong",[t._v("环境")]),t._v("：问题故障发生在本地局域网主机上安装的 mysql8.0，跑在 docker 中")]),t._v(" "),i("li",[i("strong",[t._v("问题描述")]),t._v("：本地应用连接时，查询什么的还好，但是修改数据的时候报错，错误信息是"),i("code",[t._v("lock wait timeout exceeded; try restarting transaction")])]),t._v(" "),i("li",[i("strong",[t._v("排查")]),t._v("：很明显是因为执行更新语句引起的，报错的意思是"),i("code",[t._v("超过了锁定等待超时时间；尝试重新启动事务")])]),t._v(" "),i("li",[i("strong",[t._v("解决")]),t._v("：参考 https://blog.csdn.net/zc474235918/article/details/72731363 按照文中指示，执行"),i("code",[t._v("SELECT * FROM information_schema.innodb_trx")]),t._v("查询正在运行的事务，。可以看到，这个事务状态是运行状态，并不是锁等待状态，也就是并无异常。正常情况下，如果是被锁的话 kill 掉就行，拿到"),i("code",[t._v("trx_mysql_thread_id")]),t._v("，即事务线程 id，运行"),i("code",[t._v("kill 2333")]),t._v("即可（自行替换线程 id）\n"),i("img",{attrs:{src:"https://qqadapt.qpic.cn/txdocpic/0/789e7c035c17867d28525626e3094fa8/0",alt:" "}})]),t._v(" "),i("li",[i("strong",[t._v("后续")]),t._v("：很明显这里并不是这么简单的问题，状态无问题但是仍然报错。于是我尝试新增一条数据，结果情况一样，插入超时，并且多了一条情况差不多的事务。于是尝试 kill 掉事务线程，结果立马报错"),i("code",[t._v("Lost connection to MySQL server at 'reading initial communication packet', system error: 0")]),t._v("，请看下一节\n"),i("img",{attrs:{src:"https://qqadapt.qpic.cn/txdocpic/0/cc450f5e0db6bce17a11bd77e924e795/0",alt:" "}})])]),t._v(" "),i("h2",{attrs:{id:"lost-connection-to-mysql-server-at-reading-initial-communication-packet-system-error-0"}},[i("a",{staticClass:"header-anchor",attrs:{href:"#lost-connection-to-mysql-server-at-reading-initial-communication-packet-system-error-0","aria-hidden":"true"}},[t._v("#")]),t._v(" Lost connection to MySQL server at 'reading initial communication packet', system error: 0")]),t._v(" "),i("ul",[i("li",[i("strong",[t._v("问题描述")]),t._v("：可以理解为由于 kill 掉了一个事务线程，导致需要重新连接，正常情况出现这种问题应该也是某一次发起连接的过程")]),t._v(" "),i("li",[i("strong",[t._v("排查")]),t._v("：参考： http://aiezu.com/article/mysql_error_at_reading_initial_communication_packet.html 报错信息表达的意思是在读取初始通信包时与 MySQL 服务器的连接断开。可能的原因有很多，但这里是测试环境，负载和连接不多，而且昨天还能用，那可能的原因就是资源不足了。查看了日志，果然是磁盘资源不够，所以只能读取，不能插入和修改\n"),i("img",{attrs:{src:"https://qqadapt.qpic.cn/txdocpic/0/3c935d0bf3a6a4f75181b574e2c5c622/0",alt:" "}})]),t._v(" "),i("li",[i("strong",[t._v("解决")]),t._v("：参考 https://blog.csdn.net/yjk13703623757/article/details/80283729 清理掉过大的 docker 镜像和日志，腾出空间之后，重启 mysql 服务就好啦")])]),t._v(" "),i("h2",{attrs:{id:"总结"}},[i("a",{staticClass:"header-anchor",attrs:{href:"#总结","aria-hidden":"true"}},[t._v("#")]),t._v(" 总结")]),t._v(" "),i("ul",[i("li",[t._v("解决完问题，想想这是为什么。服务好好的突然挂了，罢工了，是不是资源给的不够多，cpu 内存不够用了，亦或是并发量太大网络不好搞得应用程序压力很大，最后导致故障。")])])])},[],!1,null,null,null);e.default=r.exports}}]);